# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{igo-ruby}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = ["K.Nishi"]
  s.date = %q{2011-05-05}
  s.description = %q{
    Ruby port of Igo Japanese morphological analyzer. Igo-ruby needs Igo's binary dictionary files.
    These files created by Java programs.
    See: http://igo.sourceforge.jp/
  }
  s.email = %q{24signals@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/igo-ruby.rb",
    "lib/igo/dictionary.rb",
    "lib/igo/tagger.rb",
    "lib/igo/trie.rb",
    "lib/igo/util.rb",
    "lib/igo/version.rb"
  ]
  s.homepage = %q{http://github.com/kyow/igo-ruby}
  s.licenses = ["MIT"]
  s.rdoc_options = ["-c UTF-8", "-S", "-U"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Ruby port of Igo Japanese morphological analyzer.}
  s.test_files = [
    "spec/igo-ruby_spec.rb",
    "spec/spec_helper.rb",
    "test/test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

